### ISSUE TITLE
安装问题，缺少必须资源

### ISSUE THREAD

**Issue by zezhipeng** [X-Profiler/xprofiler#123]
缺少 xprofiler-v1.3.1-node-v83-linux-arm64.tar.gz  资源
系统 Centos7
机器 Mac Mini M1

完整日志
```
[10/15] scripts.install egg-xtransit@1.2.1 › xprofiler@^1.2.3 run "node-pre-gyp install --fallback-to-build", root: "/home/app/node_modules/_xprofiler@1.3.1@xprofiler"
node-pre-gyp http GET https://oss.npmmirror.com/dist/xprofiler/v1.3.1/xprofiler-v1.3.1-node-v83-linux-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://oss.npmmirror.com/dist/xprofiler/v1.3.1/xprofiler-v1.3.1-node-v83-linux-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for xprofiler@1.3.1 and node@14.17.5 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://oss.npmmirror.com/dist/xprofiler/v1.3.1/xprofiler-v1.3.1-node-v83-linux-arm64.tar.gz 
gyp http GET https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node/v14.17.5/node-v14.17.5-headers.tar.gz
gyp http 200 https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node/v14.17.5/node-v14.17.5-headers.tar.gz
gyp http GET https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node/v14.17.5/SHASUMS256.txt
gyp http 200 https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node/v14.17.5/SHASUMS256.txt
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/app/node_modules/_which@1.3.1@which/which.js:13:12)
gyp ERR! stack     at F (/home/app/node_modules/_which@1.3.1@which/which.js:68:19)
gyp ERR! stack     at E (/home/app/node_modules/_which@1.3.1@which/which.js:80:29)
gyp ERR! stack     at /home/app/node_modules/_which@1.3.1@which/which.js:89:16
gyp ERR! stack     at /home/app/node_modules/_isexe@2.0.0@isexe/index.js:42:5
gyp ERR! stack     at /home/app/node_modules/_isexe@2.0.0@isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.11.0-rc4+
gyp ERR! command "/home/app/node_modules/node/bin/node" "/home/app/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/app/node_modules/_xprofiler@1.3.1@xprofiler/build/binding/Release/node-v83-linux-arm64/xprofiler.node" "--module_name=xprofiler" "--module_path=/home/app/node_modules/_xprofiler@1.3.1@xprofiler/build/binding/Release/node-v83-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/app/node_modules/_xprofiler@1.3.1@xprofiler
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/app/node_modules/node/bin/node /home/app/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/app/node_modules/_xprofiler@1.3.1@xprofiler/build/binding/Release/node-v83-linux-arm64/xprofiler.node --module_name=xprofiler --module_path=/home/app/node_modules/_xprofiler@1.3.1@xprofiler/build/binding/Release/node-v83-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/app/node_modules/_@mapbox_node-pre-gyp@1.0.8@@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.11.0-rc4+
node-pre-gyp ERR! command "/home/app/node_modules/node/bin/node" "/home/app/node_modules/_xprofiler@1.3.1@xprofiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/app/node_modules/_xprofiler@1.3.1@xprofiler
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
Failed to execute '/home/app/node_modules/node/bin/node /home/app/node_modules/_node-gyp@3.8.0@node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/app/node_modules/_xprofiler@1.3.1@xprofiler/build/binding/Release/node-v83-linux-arm64/xprofiler.node --module_name=xprofiler --module_path=/home/app/node_modules/_xprofiler@1.3.1@xprofiler/build/binding/Release/node-v83-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
[npminstall:runscript:error] egg-xtransit@1.2.1 › xprofiler@^1.2.3 scripts.install run "node-pre-gyp install --fallback-to-build" error: Error [RunScriptError]: Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/tnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  stdio: [Object],
  exitcode: 1
}
Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
RunScriptError: Run "sh -c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.<anonymous> (/usr/lib/node_modules/tnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npminstall version: 5.4.0
npminstall args: /home/app/node_modules/node/bin/node /usr/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js --prefix=/usr --fix-bug-versions --forbidden-licenses=AGPL,CPAL,OSL --china -d --no-cache --tmp=/root/.tnpm_tmp --no-proxy --userconfig=/root/.tnpmrc --registry=https://registry.npm.alibaba-inc.com --disturl=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node
[tnpm] subprocess:/usr/lib/node_modules/tnpm/node_modules/npminstall/bin/install.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1
```

**Comment by hyj1991** [comment]
没有对 arm 进行编译，我手里也没有 linux arm 的环境 - -!

**Comment by hyj1991** [comment]
不过没有预编译的包，可以回退到本地编译的，只要你的机器上有编译环境就可以在安装的时候本地编译成功

**Comment by zezhipeng** [comment]
嗯 需要 g++ >= 5.2 本地编译才能成功，默认安装的 gcc 版本太低了
