### ISSUE TITLE
xprofiler coredump导出的文件andb识别不了

### ISSUE THREAD

**Issue by CreatedFromZhang** [X-Profiler/xprofiler#223]
![image](https://user-images.githubusercontent.com/42968363/230297348-549f0c19-47d9-45c3-a3c5-f44eedf7f81e.png)

xprofile 版本已经更新到了2.5.1

**Comment by hyj1991** [comment]
你用错了吧，我们一直在使用这个功能，看下你的执行指令。

**Comment by CreatedFromZhang** [comment]
andb -g -c x-coredump-3085-20230406-0.core

**Comment by zhaolei0505** [comment]
这个错误提示是 corefile 不是一个有效的 elf 文件，可以使用 file x-coredump-3085-20230406-0.core 看一下输出么？

**Comment by CreatedFromZhang** [comment]
file x-coredump-3085-20230406-0.core 
x-coredump-3085-20230406-0.core: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'node /data/project/ldap-agent/dist/index.js', real uid: 0, effective uid: 0, real gid: 0, effective gid: 0, execfn: '/bin/node', platform: 'x86_64'

**Comment by CreatedFromZhang** [comment]
andb -g -c x-coredump-3085-20230406-0.core 
/data/project/andb/loader
error: not a valid elf file.
Traceback (most recent call last):
  File "/data/project/andb/loader", line 124, in <module>
    buildId = corefileFmt.GetBuildId()
  File "/data/project/andb/andb/loader/core.py", line 121, in GetBuildId
    return prog.GetBuildId()
  File "/data/project/andb/andb/loader/elf.py", line 510, in GetBuildId
    for (name, desc, n_type) in self.GetNotes():
  File "/data/project/andb/andb/loader/elf.py", line 336, in GetNotes
    for p in self.GetPhdrs():
  File "/data/project/andb/andb/loader/elf.py", line 280, in GetPhdrs
    m = self.Seek(off)
  File "/data/project/andb/andb/loader/elf.py", line 196, in Seek
    m.seek(x)
ValueError: seek out of range

**Comment by CreatedFromZhang** [comment]
gdb --version
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by zhaolei0505** [comment]
`/bin/node` 这是官方的 node 么？版本号是多少？

**Comment by CreatedFromZhang** [comment]
/bin/node  --version
v16.17.0  是用nvm 安装的

**Comment by zhaolei0505** [comment]
可以直接从这个地址获取 node.typ。
[node-v16.17.0.typ.gz](https://alinode-debugger-info.oss-cn-zhangjiakou.aliyuncs.com/dwf/by-version/node-v16.17.0/node.typ.gz)

然后将您本地的 /bin/node 和 x-coredump-3085-20230406-0.core 放在同一个目录下。
使用以下命令启动本地调试，默认 andb 会查找和加载当前目录下的 node.typ 文件。
```
andb -g node -c x-coredump-3085-20230406-0.core
```

**Comment by CreatedFromZhang** [comment]
![image](https://user-images.githubusercontent.com/42968363/230329922-c237139f-6769-4bf2-9dd8-c42decb6b079.png)

**Comment by zhaolei0505** [comment]
运行环境是什么？ 另外看一下 andb 是最新 main 的代码么？因为上面的行号和我看的对应不上。

**Comment by zhaolei0505** [comment]
andb 项目地址在： https://github.com/noslate-project/andb

**Comment by CreatedFromZhang** [comment]
git remote -v
origin  https://github.com/noslate-project/andb.git (fetch)
origin  https://github.com/noslate-project/andb.git (push)
git log 
commit 99b365b52297ec3d067c272139aeba9d5b3868ec
Author: ZhaoLei <77103671+zhaolei0505@users.noreply.github.com>
Date:   Tue Mar 21 11:06:02 2023 +0800

    feat: added environ, isolate and mmap note in tsr. (#33)

commit c503c258cc19f26a2199b28add72d489a497c131
Author: ZhaoLei <77103671+zhaolei0505@users.noreply.github.com>
Date:   Wed Mar 15 12:54:00 2023 +0800

 git status -v
# On branch main
nothing to commit, working directory clean


应该是最新的吧，用的主分支的代码

**Comment by zhaolei0505** [comment]
或者试试删干净 andb 后 git reset 看看？因为这个错误我这边没有遇到过

**Comment by zhaolei0505** [comment]
上面的错误，似乎是你的环境可以在 gdb 导入 lldb 的包导致?

```
(gdb) import lldb
Undefined command: "import".  Try "help".
(gdb) sc
Undefined command: "sc".  Try "help".
(gdb) pi
>>> import lldb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lldb
>>>
```

如果你本机上也安装了 lldb，可以去掉 -g (gdb) 选项直接使用 lldb 调试看看

**Comment by CreatedFromZhang** [comment]
![image](https://user-images.githubusercontent.com/42968363/230336470-c3f9e8e8-a15e-4c4b-91bb-6a1c4b29e93c.png)
gcore 支持lldb吗？因为这个coredump是xprofIler生成的

**Comment by zhaolei0505** [comment]
lldb 的版本是多少？lldb --version，如果太低可能不支持 node.typ 文件。
如果需要使用 gdb 的话，可以先临时把 andb/andb/dbg/dbg_select.py 去掉 lldb 的支持，
```
type = 'unknown'
if isGDB():
    from .dbg_gdb import *
    type = "gdb"
else:
    raise Exception
```

**Comment by CreatedFromZhang** [comment]
lldb --version
lldb version 3.4.2 ( revision )

**Comment by CreatedFromZhang** [comment]
![image](https://user-images.githubusercontent.com/42968363/230341454-8bce388b-ec4c-449d-93d8-43a216b3f68a.png)
注释掉了，不过好像缺少了python包

**Comment by zhaolei0505** [comment]
gdb 用 andb-gdb 的项目试试？
https://github.com/noslate-project/andb-gdb

```
cd andb-gdb
source env.sh
```

**Comment by zhaolei0505** [comment]
> lldb --version lldb version 3.4.2 ( revision )

需要 7.0 以上版本

**Comment by CreatedFromZhang** [comment]
![image](https://user-images.githubusercontent.com/42968363/230347412-c439ec1c-f2ed-4769-97a7-1c63d4f197b6.png)
没有报错了，不过这个工具怎么查看v8对象呢

**Comment by zhaolei0505** [comment]
> ![image](https://user-images.githubusercontent.com/42968363/230347412-c439ec1c-f2ed-4769-97a7-1c63d4f197b6.png) 没有报错了，不过这个工具怎么查看v8对象呢

启动命令发一下？ 这个好像只是启动了 gdb，并没有加载 andb ？

正常的启动会显示 v8 的版本，以及加载的 v8 对象信息。
![image](https://user-images.githubusercontent.com/77103671/230356473-60c9ad56-f158-48c9-b8d9-1f8f2ba221b1.png)

最后会有 andb loaded 字样
![image](https://user-images.githubusercontent.com/77103671/230356784-ce701efc-7b7d-4ec1-8a10-f0625e4023dd.png)

**Comment by CreatedFromZhang** [comment]
![image](https://user-images.githubusercontent.com/42968363/230523200-99c7719e-675b-498c-964a-e6450a24715c.png)

**Comment by zhaolei0505** [comment]
看下你的 node 文件？执行下命令，
```
nm -C node | grep major
file node
```

**Comment by CreatedFromZhang** [comment]
nm -C /bin/node | grep major
nm: /bin/node: no symbols
file /bin/node
/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=5c066306816aaaf4548082844e1ba677268a1669, for GNU/Linux 2.6.32, stripped

**Comment by zhaolei0505** [comment]
> nm -C /bin/node | grep major nm: /bin/node: no symbols file /bin/node /bin/node: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=5c066306816aaaf4548082844e1ba677268a1669, for GNU/Linux 2.6.32, stripped

这个 node 版本不是 node.js 官方的 release，目前 andb 仅支持对官方 release 的版本产生的 coredump 进行分析。另外不要对 node 的二进制进行 strip 操作，strip 之后就无法进行调试了。

**Comment by CreatedFromZhang** [comment]
感谢各位大佬的支持！
